root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/bin/server ./cmd/server"
bin = "tmp/bin/server"
delay = 500
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go", "mod", "sum", "proto"]
include_dir = ["cmd", "internal", "pkg", "proto"]
stop_on_error = true

[log]
main_only = true
time = true

[env]
CONFIG_PATH = "assets/local-compose.yaml"
