services:
  server:
    build:
      context: .
      dockerfile: docker/dev/server/Dockerfile
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: air -c .air.toml
    ports:
      - "50051:50051"
    environment:
      - GO111MODULE=on
      - CONFIG_PATH=assets/local-compose.yaml
    depends_on:
      - postgres
    profiles:
      - local
      - ci
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - local
      - ci
volumes:
  postgres-data:
  go-mod-cache:
  go-build-cache:
