name: CI

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: '1.25.3'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run unit tests
        run: go test ./...

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download modules
        run: go mod download

      - name: Run integration tests
        env:
          CONFIG_PATH: ${{ github.workspace }}/assets/ci.yaml
          COMPOSE_PROFILE: ci
        run: ./scripts/ci/run_integration.sh
